### ISSUE TITLE
Node throws an error on initial connection

### ISSUE THREAD

**Issue by giedriusStan** [yankee42/node-red-contrib-daikin-ac#1]
Everything seams to work fine for me, even though the node does throw an error:

![2021-05-14_10-21](https://user-images.githubusercontent.com/1705190/118236007-301d6f80-b49e-11eb-9096-266d67b8f466.png)

"Could not get basic info: Cannot parse response: ret":"OK","type":"aircon","reg":"eu","dst":"1","ver":"1_2_54","rev":"203DE8C","pow":"1","err":"0","location":"0","name":"%4d%69%65%67%61%6d%6f%6a%6f%20%41%43","icon":"5","method":"polling","port":"30050","id":"acup48","pw":"1a9c1uhy","lpw_flag":"0","adp_kind":"3","pv":"3.30","cpv":"3","cpv_minor":"20","led":"0","en_setzone":"1","mac":"80C5F2101B67","adp_mode":"run","en_hol":"0","ssid1":"(\/) (°","","°) (\/)","radio1":"-55","grp_name":"","en_grp":"0"

**Comment by yankee42** [comment]
Is the SSID of your WiFi network actually `(/) (°,,°) (/)`? :-D. Funny. Well, the comma in the ssid confuses the response parser. Which method did you call?

**Comment by giedriusStan** [comment]
Yes, I figured my SSID could be the issue :) I get this error regardless of the method, but in this case I'm calling getACSensorInfo

**Comment by yankee42** [comment]
OK. Howver it is really a problem with the Daikin-Controller library that I just wrap here. I created a [pull request](https://github.com/Apollon77/daikin-controller/pull/107) there to fix that. I don't know how long it will take for the author to look into it.

**Comment by giedriusStan** [comment]
gatcha, thanks for looking at it!

**Comment by yankee42** [comment]
Apollon77 was pretty fast in merging my PR. So I updated the project and this should be fixed in 1.0.3.
