### ISSUE TITLE
Add 'mompow' to getACSensorInfo

### ISSUE THREAD

**Issue by bjornstevens** [yankee42/node-red-contrib-daikin-ac#2]
Hi, while using the url way to get data i got this back;
ret=OK,htemp=20.0,hhum=-,otemp=25.0,err=0,cmpfreq=0,mompow=1

after some research I found out mompow means this:
mompow: Current (momentary) power usage (in kW, 100W resolution). Forced to 0 is the unit is turned off, as most units seem to report a 100W value in idle mode, even though the unit does not consume anywhere close to 100W while turned off. 

Are you able to add this?
Thanks!

**Comment by yankee42** [comment]
This library is only a small wrapper for [daikin-controller](https://github.com/Apollon77/daikin-controller) that makes daikin-controller "nodeRED-ready". To support this feature this would need to be added to the daikin-controller lib. So you need to propose this there. When this is added to daikin-controller I can just bump the version to make this available with this wrapper.

**Comment by bjornstevens** [comment]
Ahh, I see. Thanks!
